In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.shape

(8173, 46)

In [4]:
df.columns

Index(['id', 'event_type', 'latitude', 'longitude', 'endlatitude',
       'endlongitude', 'address', 'end_address', 'event_cause',
       'requires_road_closure', 'start_datetime', 'end_datetime', 'status',
       'authenticated', 'modified_datetime', 'map_file', 'direction',
       'description', 'veh_type', 'veh_no', 'corridor', 'priority',
       'cargo_material', 'reason_breakdown', 'age_of_truck', 'created_date',
       'route_path', 'client_id', 'created_by_id', 'last_modified_by_id',
       'assigned_to_police_id', 'citizen_accident_id', 'comment',
       'police_station', 'meta_data', 'kgid', 'resolved_at_address',
       'resolved_at_latitude', 'resolved_at_longitude', 'closed_by_id',
       'closed_datetime', 'resolved_by_id', 'resolved_datetime',
       'gba_identifier', 'zone', 'junction'],
      dtype='object')

In [5]:
df.shape

(8173, 46)

In [6]:
df.head()

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FKID000001,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,...,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",12.921876,77.645158,NaN,NaN,FKUSR00002,2024-01-30 04:17:46.828355+00,NaN,NaN,NaN
2,FKID000002,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 04:56:03.281509+00,NaN,NaN,Bengaluru Central Corporation,Central Zone 2,UrvashiJunction
3,FKID000003,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,...,NaN,NaN,NaN,FKUSR00004,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN,NaN,NaN
4,FKID000004,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,FKUSR00003,2024-01-30 05:35:17.338283+00,NaN,NaN,NaN,NaN,LalbaghMainGateJunc

In [9]:
df.isnull().sum()

id                          0
event_type                  0
latitude                    0
longitude                   0
endlatitude               169
endlongitude              169
address                     3
end_address              7486
event_cause                 0
requires_road_closure       0
start_datetime              0
end_datetime             7683
status                      0
authenticated               0
modified_datetime           0
map_file                 8173
direction                8130
description              1360
veh_type                 3286
veh_no                   3287
corridor                   20
priority                    2
cargo_material           7897
reason_breakdown         7897
age_of_truck             7897
created_date                0
route_path               8036
client_id                   0
created_by_id               2
last_modified_by_id         3
assigned_to_police_id    8045
citizen_accident_id      8045
comment                  8173
police_station              0
meta_data                8173
kgid                      259
resolved_at_address      8099
resolved_at_latitude     8099
resolved_at_longitude    8099
closed_by_id             5032
closed_datetime          5032
resolved_by_id           8099
resolved_datetime        8099
gba_identifier           4729
zone                     4729
junction                 5663
dtype: int64

In [16]:
df['direction'].unique()

array([nan, 'north', 'west', 'north_west', 'south_west', 'south',
       'north_east', 'east', 'south_east'], dtype=object)

In [20]:
df.drop(
    ['direction',
     'resolved_datetime',
     'resolved_by_id',
     'resolved_at_longitude',
     'resolved_at_latitude',
     'resolved_at_address',
     'meta_data',
     'citizen_accident_id',
     'assigned_to_police_id',
     'route_path',
     'age_of_truck',
     'reason_breakdown',
     'cargo_material',
     'map_file'],
    axis=1,
    inplace=True
)

In [21]:
df.shape

(8173, 32)

In [25]:
df.drop(['end_address','end_datetime','comment','closed_by_id','closed_datetime','gba_identifier','zone','junction'], axis=1, inplace=True)

In [26]:
df.isnull().sum()

id                          0
event_type                  0
latitude                    0
longitude                   0
endlatitude               169
endlongitude              169
address                     3
event_cause                 0
requires_road_closure       0
start_datetime              0
status                      0
authenticated               0
modified_datetime           0
description              1360
veh_type                 3286
veh_no                   3287
corridor                   20
priority                    2
created_date                0
client_id                   0
created_by_id               2
last_modified_by_id         3
police_station              0
kgid                      259
dtype: int64

In [28]:
df.shape

(8173, 24)

In [34]:
df.drop(['veh_no','kgid','created_by_id'], axis=1, inplace=True)

In [64]:
df.drop('description', axis=1, inplace=True)

In [ ]:
df.drop('last_modified_by_id', axis=1, inplace=True)

In [82]:
df.drop('id',axis=1,inplace=True)

In [83]:
df.isnull().sum()

event_type               0
latitude                 0
longitude                0
endlatitude              0
endlongitude             0
address                  0
event_cause              0
requires_road_closure    0
start_datetime           0
status                   0
authenticated            0
modified_datetime        0
veh_type                 0
corridor                 0
priority                 0
created_date             0
client_id                0
police_station           0
dtype: int64

In [62]:
df['veh_type'].fillna(df['veh_type'].mode()[0], inplace=True)
df['priority'].fillna(df['priority'].mode()[0], inplace=True)
df['corridor'].fillna(df['corridor'].mode()[0], inplace=True)
df['endlatitude'].fillna(df['endlatitude'].mode()[0], inplace=True)
df['endlongitude'].fillna(df['endlongitude'].mode()[0], inplace=True)

C:\Users\nik16\AppData\Local\Temp\ipykernel_36504\3784280321.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['endlatitude'].fillna(df['endlatitude'].mode()[0], inplace=True)
C:\Users\nik16\AppData\Local\Temp\ipykernel_36504\3784280321.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['endlongitude'].fillna(df['endlongitude'].mode()[0], inplace=True)

In [70]:
df.dropna(inplace=True)

In [92]:
df['police_station'].unique()

array(['Peenya', 'HSR Layout', 'Wilson Garden', 'Sadashivanagar',
       'Hebbala', 'Kengeri', 'Cubbon Park', 'Hennuru', 'K.R. Pura',
       'Byatarayanapura', 'Mahadevapura', 'Halasur', 'Kodigehalli',
       'Jayanagara', 'Madiwala', 'Jeevanbheemanagar', 'Whitefield',
       'Shivajinagar', 'Mico Layout', 'HAL Old Airport', 'J.P. Nagar',
       'Magadi Road', 'Electronic City', 'High ground', 'Chikkabanavara',
       'K.G. Halli', 'Yeshwanthpura', 'Bellandur', 'Malleshwaram',
       'Devanahalli Airport', 'Jnanabharathi', 'Vijayanagara',
       'Chamarajpet', 'Kamakshipalya', 'V.V.Puram (C.Pet)', 'Rajajinagar',
       'No Police Station', 'Pulikeshinagar(F.Town)', 'Adugodi',
       'Ashok Nagar', 'Banaswadi', 'Halasuru Gate', 'R.T. Nagar',
       'Banashankari', 'City Market', 'Basavanagudi', 'Yelahanka',
       'K.S. Layout', 'Chikkajala', 'Sheshadripuram', 'Hulimavu',
       'Jalahalli', 'Thalagattapura', 'Upparpet'], dtype=object)

In [85]:
df.head(1)

,event_type,latitude,longitude,endlatitude,endlongitude,address,event_cause,requires_road_closure,start_datetime,status,authenticated,modified_datetime,veh_type,corridor,priority,created_date,client_id,police_station
0,unplanned,13.040004,77.518099,0.0,0.0,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",vehicle_breakdown,False,2024-03-07 17:01:48.111+00,closed,yes,2024-03-07 19:35:47.871698+00,lcv,Tumkur Road,High,2024-03-07 17:03:51.164032+00,1,Peenya

In [93]:
df = pd.get_dummies(df, columns=['event_type', 'event_cause','requires_road_closure','status','authenticated','veh_type','corridor','priority','police_station'], drop_first=True)

In [94]:
df.head()

,latitude,longitude,endlatitude,endlongitude,address,start_datetime,modified_datetime,created_date,client_id,event_type_unplanned,...,police_station_Sheshadripuram,police_station_Shivajinagar,police_station_Thalagattapura,police_station_Upparpet,police_station_V.V.Puram (C.Pet),police_station_Vijayanagara,police_station_Whitefield,police_station_Wilson Garden,police_station_Yelahanka,police_station_Yeshwanthpura
0,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",2024-03-07 17:01:48.111+00,2024-03-07 19:35:47.871698+00,2024-03-07 17:03:51.164032+00,1,True,...,False,False,False,False,False,False,False,False,False,False
1,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",2024-01-30 04:07:24.173+00,2024-01-30 04:17:46.828979+00,2024-01-30 04:08:22.954979+00,1,True,...,False,False,False,False,False,False,False,False,False,False
2,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",2023-11-11 06:18:03.343+00,2024-01-30 04:56:03.282003+00,2023-11-11 06:20:00.989398+00,1,True,...,False,False,False,False,False,False,False,True,False,False
3,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...",2024-03-07 17:56:55.061+00,2024-03-14 07:42:05.55005+00,2024-03-07 17:58:56.696892+00,1,True,...,False,False,False,False,False,False,False,False,False,False
4,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",2024-01-30 04:56:32.348+00,2024-01-30 05:35:17.33908+00,2024-01-30 04:58:55.937662+00,1,True,...,False,False,False,False,False,False,False,True,False,False

In [97]:
df['start_datetime'] = pd.to_datetime(df['start_datetime'])

ValueError: time data "2024-02-12 02:05:46+00" doesn't match format "%Y-%m-%d %H:%M:%S.%f%z", at position 8. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
df['modified_datetime'] = pd.to_datetime(df['modified_datetime'])
df['created_date'] = pd.to_datetime(df['created_date'])

In [99]:
df['start_datetime'] = pd.to_datetime(
    df['start_datetime'],
    format='mixed'
)
df['modified_datetime'] = pd.to_datetime(
    df['modified_datetime'],
    format='mixed'
)

df['created_date'] = pd.to_datetime(
    df['created_date'],
    format='mixed'
)

In [100]:
# start_datetime features
df['start_year'] = df['start_datetime'].dt.year
df['start_month'] = df['start_datetime'].dt.month
df['start_day'] = df['start_datetime'].dt.day
df['start_hour'] = df['start_datetime'].dt.hour
df['start_dayofweek'] = df['start_datetime'].dt.dayofweek

# modified_datetime features
df['modified_year'] = df['modified_datetime'].dt.year
df['modified_month'] = df['modified_datetime'].dt.month
df['modified_day'] = df['modified_datetime'].dt.day
df['modified_hour'] = df['modified_datetime'].dt.hour

# created_date features
df['created_year'] = df['created_date'].dt.year
df['created_month'] = df['created_date'].dt.month
df['created_day'] = df['created_date'].dt.day
df['created_dayofweek'] = df['created_date'].dt.dayofweek

In [101]:
df['modify_delay_hours'] = (
    df['modified_datetime'] - df['start_datetime']
).dt.total_seconds() / 3600

df['creation_to_start_hours'] = (
    df['start_datetime'] - df['created_date']
).dt.total_seconds() / 3600

In [102]:
df.drop(
    columns=['start_datetime', 'modified_datetime', 'created_date'],
    inplace=True
)

In [109]:
df.drop('address', axis=1, inplace=True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8170 entries, 0 to 8172
Columns: 126 entries, latitude to creation_to_start_hours
dtypes: bool(105), float64(6), int32(13), int64(1), object(1)
memory usage: 1.8+ MB

In [111]:
df.head()

,latitude,longitude,endlatitude,endlongitude,client_id,event_type_unplanned,event_cause_Fog / Low Visibility,event_cause_accident,event_cause_congestion,event_cause_construction,...,modified_year,modified_month,modified_day,modified_hour,created_year,created_month,created_day,created_dayofweek,modify_delay_hours,creation_to_start_hours
0,13.040004,77.518099,0.000000,0.000000,1,True,False,False,False,False,...,2024,3,7,19,2024,3,7,3,2.566600,-0.034181
1,12.921876,77.645158,0.000000,0.000000,1,True,False,False,False,False,...,2024,1,30,4,2024,1,30,1,0.172960,-0.016328
2,12.955622,77.585708,0.000000,0.000000,1,True,False,False,False,False,...,2024,1,30,4,2023,11,11,5,1918.633316,-0.032680
3,13.006147,77.579435,13.006239,77.579516,1,True,False,False,False,False,...,2024,3,14,7,2024,3,7,3,157.752914,-0.033788
4,12.953980,77.585233,0.000000,0.000000,1,True,False,False,False,False,...,2024,1,30,5,2024,1,30,1,0.645831,-0.039886

In [113]:
df.shape

(8170, 125)